development:
  host: localhost
  database: hdata_server_development

test:
  host: <%= ENV['TEST_DB_HOST'] || 'localhost' %>
  database: hdata_server_test

staging:
  host: localhost
  database: hdata_server_staging

production:
  host: localhost
  database: hdata_server_production
