development:
  host: localhost
  database: hdata_server_development

test:
  host: localhost
  database: hdata_server_test

production:
  uri: <%= ENV['MONGOHQ_URL'] %>
  database: hdata_server_production
